### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by AlexanderRMcNeill** [alexandrory/postitlocs_ui#1]

**Comment by AlexanderRMcNeill** [comment]
Sup bro

**Comment by RoryMearns** [comment]
Yo @AlexanderRMcNeill I seem to remember you linking some .gitignore thing when setting up this repo. Is that so? Should there still be a .gitignore that pulls to my local repo to keep git tidy there too? Cheers

**Comment by AlexanderRMcNeill** [comment]
Didn't add one yet sorry. This one should work https://github.com/coryhouse/pluralsight-redux-starter might have more than we need though

**Comment by RoryMearns** [comment]
Ah, awesome. I didn't want to mess something up if you already had. Will have a look at that one.

**Comment by AlexanderRMcNeill** [comment]
This is what I set up for PR tinder if you want a reference https://github.com/AlexanderMcNeill/pr-tinder

**Comment by RoryMearns** [comment]
👍
